version: '3.9'

services:
  meals:
    build: .
    image: fast-api-meal
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=new_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=meal_db
      - POSTGRES_HOST=localhost
      - "POSTGRES_HOST_AUTH_METHOD=trust"

    expose:
      - 5432

volumes:
  pgdata:

